### ISSUE TITLE
IsBetweenInclusive should allow  from==to

### ISSUE THREAD

**Issue by Finomosec** [cirneco/cirneco#8]
When using `it.ozimov.cirneco.hamcrest.java7.J7Matchers.betweenInclusive(Integer, Integer)` it should allow to pass `from==to`.

Example: `assertThat(5, J7Matchers.betweenInclusive(5, 5));`

Looks completely consistent to me.

Currently i get this error:
```
java.lang.IllegalArgumentException: from must be before to
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at it.ozimov.cirneco.hamcrest.java7.base.IsBetweenInclusive.<init>(IsBetweenInclusive.java:27)
	at it.ozimov.cirneco.hamcrest.java7.base.IsBetweenInclusive.betweenInclusive(IsBetweenInclusive.java:50)
	at it.ozimov.cirneco.hamcrest.java7.J7Matchers.betweenInclusive(J7Matchers.java:85)
```

p.s. the error message could/should contain the given values to be more useful.
For example like this:
`checkArgument(from.compareTo(to) <= 0, "from must be before to or equal. from: %s, to: %s", from, to);`

**Comment by robertotru** [comment]
Hi @Finomosec .

Thanks for writing. 
It is questionable. I'd better say that you should use equality when from == to.  Anyway, if I change the API now I could break others test. I'm not convinced that this would be a good.

I have to think about it. Anyway, feel free to open a pull request!

**Comment by robertotru** [comment]
I'll close this due to inactivity.
